<?php
// ******** ARCHIVOS DE CONFIGURACION DE CONTEXTOS DEL MOODLE V1.9 Y V2.2
// ******** ESTE PUEDE CAMBIAR EN VERSIONES FUTURAS
define('CONTEXT_USER', 30); // VALOR DEL CONTEXTO DE UN USUARIO EN MOODLE
define('CONTEXT_COURSECAT', 40); // VALOR DEL CONTEXTO DE LAS CATEGORIAS DEL MOODLE
define('CONTEXT_COURSE', 50); // VALOR DEL CONTEXTO DE LOS CURSOS DE MOODLE
define('CONTEXT_BLOCK', 80);  // VALOR DEL CONTEXTO DE BLOQUEO DE OBJETOS EN EL MOODLE

define('TEACHER_ROLE','3');  //  VALOR DEL CONTEXTO DE ROL DE MAESTRO EN MOODLE
define('STUDENT_ROLE','5');  //  VALOR DEL CONTEXTO DE ROL DE ESTUDIANTE EN MOODLE

class MoodleConstants{}
?>